<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!-- After publish, copy the native binary to under the out folder as a .node file. -->
  <Target Name="PutNodeAddon" AfterTargets="Publish">
    <Copy SourceFiles="$(NativeBinary)" DestinationFiles="$(MSBuildProjectDirectory)\out\$(TargetName).node" />
	<Message Text="Copied Node.js native addon to $(MSBuildProjectDirectory)\out\$(TargetName).node" Importance="high" />
  </Target>

</Project>
